default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: roscosmos_probes_development

test:
  <<: *default
  database: roscosmos_probes_test

production:
  <<: *default
  database: roscosmos_probes_production
